name: zipting
description: zipting project

publish_to: "none"

version: 1.0.0+4

environment:
    sdk: ">=2.15.1 <3.0.0"

dependencies:
    flutter:
        sdk: flutter
    flutter_localizations:
        sdk: flutter

    cupertino_icons: ^1.0.4
    intl: ^0.17.0
    get: ^4.6.1
    get_storage: ^2.0.3
    dio: ^4.0.4
    http: ^0.13.4
    cached_network_image: ^3.2.0
    flutter_svg: ^1.0.0
    like_button: ^2.0.4
    flutter_rating_bar: ^4.0.0
    custom_radio_grouped_button: ^2.1.1
    carousel_slider: ^4.0.0
    scroll_navigation: ^1.3.2
    logger: ^1.1.0
    url_strategy: ^0.2.0
    retrofit: ^3.0.1
    email_validator: ^2.0.1
    shimmer: ^2.0.0
    flutter_map: ^0.14.0
    latlong2: ^0.8.1
    image_picker: ^0.8.4+4

dev_dependencies:
    flutter_test:
        sdk: flutter
    change_app_package_name: any

    lints: ^1.0.1
    flutter_lints: ^1.0.0

flutter:
    uses-material-design: true

    assets:
        - assets/
        - assets/images/
        - assets/icons/
        - assets/images/room_detail/
        - assets/icons/room_detail/
        - assets/icons/room_detail/opponent/
        - assets/icons/mypage/
